name       : linux-current
version    : 5.4.1
release    : 137
source     :
    - https://cdn.kernel.org/pub/linux/kernel/v5.x/linux-5.4.1.tar.xz : a7d48bb324d53e421ffbe4da40087b3c0c5112707e5f3d827c30118542c74fd9
license    :
    - GPL-2.0-only
component  :
    - kernel.image
    - headers : kernel.devel
summary    :
    - Linux kernel image and modules (current)
    - headers : Linux kernel headers (current)
description:
    - The Linux kernel and modules, the core of the operating system
    - headers : Headers required for building out of tree kernel modules
builddeps  :
    - pkgconfig(devmapper)
    - pkgconfig(libelf)
    - bc
    - btrfs-progs
    - cpio
    - dracut
    - intel-microcode
    - kbd
    - linux-firmware
    - lz4
    - perl
    - prelink
patterns   :
    - headers : /usr/src
permanent  :
    - /lib/modules
    - /usr/lib/kernel
    - /usr/src
replaces   :
    - kernel
    - kernel-modules
    - headers : kernel-headers
setup      : |
    %apply_patches
    # Set the version
    extraVersion="-${release}.current"
    sed -e "s/EXTRAVERSION =.*/EXTRAVERSION = $extraVersion/" -i Makefile

    # Ensure config is valid
    install $pkgfiles/config .config
    %make ARCH=x86_64 oldconfig
build      : |
    %make ARCH=x86_64 CONFIG_DEBUG_SECTION_MISMATCH=y
    %make -C tools/objtool
install    : |
    # Install kernel blob
    kernID="com.solus-project.current"
    kversion="${version}-${release}.current"
    install -D -m 0755 arch/x86/boot/bzImage $installdir/usr/lib/kernel/$kernID.${version}-${release}

    # Install additional files
    install -m 00644 .config $installdir/usr/lib/kernel/config-$kversion
    install -m 00644 System.map $installdir/usr/lib/kernel/System.map-$kversion
    install -m 00644 $pkgfiles/cmdline $installdir/usr/lib/kernel/cmdline-$kversion

    # Install kernel modules, disable depmod + firmware install
    install -D -d -m 00755 $installdir/lib/modules/$kversion
    %make ARCH=x86_64 INSTALL_MOD_PATH=$installdir/ modules_install KERNELRELEASE=$kversion mod-fw= DEPMOD=/bin/true

    # Remove broken links
    rm -v $installdir/lib/modules/${kversion}/{source,build}

    # Mark this as the default "current" kernel
    ln -sv $kernID.${version}-${release} $installdir/usr/lib/kernel/default-current

    # Fix mods
    depmod -b $installdir/ $kversion -a

    # Store vendor initrd within the kernel package, prevent mangling from fakeroot
    LD_PRELOAD='' dracut --strip --tmpdir /tmp -N -f  \
        --kmoddir $installdir/lib/modules/${kversion} \
        --kver $kversion --add "bash systemd lvm dm rescue" \
        --prelink --strip --hardlink \
        --nomdadmconf --early-microcode \
        $installdir/usr/lib/kernel/initrd-$kernID.${version}-${release}

    # Install the headers
    tgtDir="/usr/src/linux-headers-$kversion"
    dstDir="$installdir/$tgtDir"
    install -D -d -m 00755 $dstDir
    find . -path './include/*' -prune -o -path './scripts/*' -prune -o -path './Documentation/*' -prune -o -type f \( -name 'Makefile*' -o -name 'Kconfig*' -o -name 'Kbuild*' -o -name '*.sh' -o -name '*.pl' -o -name '*.lds' \) -print | cpio -pVd --preserve-modification-time $dstDir/

    # Necessary for out of tree modules
    for h in "drivers/media/dvb-frontends" "drivers/media/tuners" "drivers/media/platform"; do
        install -D -d -m 00755 $dstDir/$h
        cp -a $h/*.h $dstDir/$h
    done

    # For a full headers pkg
    for p in "include" "scripts" "Documentation"; do
        cp -a $p $dstDir
    done

    # Nuke any unneeded bits.
    rm -f $dstDir/scripts/*.o
    rm -f $dstDir/scripts/*/*.o
    rm -rf $dstDir/Documentation/DocBook

    # Copy remaining include dirs
    (find arch -name include -type d -print | xargs -n1 -i: find : -type f) | cpio -pd --preserve-modification-time "$dstDir"

    # Shove last bits needed for out of tree kernel builds
    install -m 00644 Module.symvers $dstDir/.
    install -m 00644 System.map $dstDir/.
    install -m 00644 .config $dstDir/.config

    # Add objtool binary for CONFIG_STACK_VALIDATION (T5607)
    install -m 00755 tools/objtool/objtool $dstDir/tools/objtool/objtool

    # Fix up build/source links
    ln -sv build $installdir/lib/modules/$kversion/source
    ln -sv $tgtDir $installdir/lib/modules/$kversion/build
